#!/bin/bash

# 
mvn -T 1.5C clean install -Dmaven.test.skip=true
cd target/
mvn install:install-file -Dfile=opensyd-pagseguro-3.1.1.jar -DgroupId=com.venosyd.open -DartifactId=opensyd-pagseguro -Dversion=3.1.1 -Dpackaging=jar
